### ISSUE TITLE
Support for iPhone SE 2020 ?

### ISSUE THREAD

**Issue by nakheel77** [ryannair05/Little11#131]
I tried many ways to take gesture or feartures iPhone X on my device without jailbreak, but all failed ! ( it is apear redbar on stausbar )

Maybe, this is the last way i want to try! but my device un-jail! Can i have .ipa to try it? 

Many thanks!

**Comment by akaROOSTA** [comment]
Dang playa I sympathize for your struggle

I'm pretty absolutely sure that you have to jailbreakyour device although I think I remember seeing that you can now tinker a tad bit with gesture types recently 🤔....

**Comment by akaROOSTA** [comment]
I've been using the tweaks bundled up into one package called Orion from Chariz which has like at least a hundred different tweaks all into this ONE TWEAK... But in terms of what Little11 has to offer, I'm starting to really dig its ways for having the newer iPhone gesture style onton the older iPhones (I'm sportin the iPhone 📱 SE 2020 on iOS 13.5 - the best for this type)

**Comment by ryannair05** [comment]
A jailbreak is required to use Little11. It will not be supported un-jailbroken or through an .ipa
