### ISSUE TITLE
Crash when using unc0ver jailbreak 

### ISSUE THREAD

**Issue by wqhqq1** [ryannair05/Little11#15]
If I use it for unc0ver jailbreak ,I will get into Safe Mode

**Comment by keepitstreet1251** [comment]
Same

**Comment by abheizthe** [comment]
iPhone 6S iOS 13.3. jailbreak by Unc0ver 4.2.1 version
Little11 1.2.0 version

crash and put me in Safe Mode too

but, installing 1.0.1 version work perfectly
