### ISSUE TITLE
Big Keyboard enabled in snapchat when option is turned off

### ISSUE THREAD

**Issue by MistryM4chine** [ryannair05/Little11#17]
iPhone 7 Plus 
iOS 13.3.1
Checkra1n
Little 11 version 1.2.0

I have the option for larger keyboard disabled in little 11 preferences. It works correctly in all apps, however in snapchat the large keyboard is enabled for some reason. I also use Choicy to disable all tweak injection in snapchat. However, little 11 still enables large keyboard in snapchat for some reason.

Thanks very much :)

![2EE2C12A-1CE4-463E-AEC0-410FA9C30C07](https://user-images.githubusercontent.com/57872364/75483281-6f959400-599e-11ea-879e-2dfd9e34e061.jpeg)

**Comment by ryannair05** [comment]
This happens because you have Choicy, a tweak that disables tweak injection, enabled for Snapchat. To fix this, don't disable injection inside of Snapchat. Unfortunately, there is no other way, that I am aware of, to fix this issue.
