### ISSUE TITLE
Screenshot still not working on iphone 6s version 1.2.1

### ISSUE THREAD

**Issue by yoguboss** [ryannair05/Little11#20]
Screenshot still aren’t working on iphone 6s Little11, 1.2.1

**Comment by slavko989** [comment]
I confirm this on iphone 6s 13.3 checkrain too.

**Comment by yoguboss** [comment]
> I confirm this on iphone 6s 13.3 checkrain too.

I’m on 13.3.1 and using checkra1n

**Comment by yoguboss** [comment]
> > I confirm this on iphone 6s 13.3 checkrain too.
> 
> I’m on 13.3.1 and using checkra1n

I have 2 iphone 6s both on 13.3.1 and checkra1n but it’s not working
