### ISSUE TITLE
1.2.1 breaks landscape mode games. 

### ISSUE THREAD

**Issue by batfirex2** [ryannair05/Little11#21]
Updated and when I try and play landscape games, it’s like the UI is shifted to the left and it gets cut off. Downgrading fixes the issue.

**Comment by batfirex2** [comment]
![CECF5354-E831-4777-8846-735610060BBF](https://user-images.githubusercontent.com/57993479/76048208-2a8bd780-5f33-11ea-863e-4e670b96acca.png)
![9A5003FA-FAF3-4E06-8BFD-2B8821B058F1](https://user-images.githubusercontent.com/57993479/76048210-2bbd0480-5f33-11ea-8f33-e82306282caf.png)

**Comment by riceramen** [comment]
It seems like bottom inset is the cause. I disabled bottom inset to fix it. Little11 version 1.2.1

**Comment by batfirex2** [comment]
I’ll reupdate on my device and disable bottom inset.

**Comment by batfirex2** [comment]
It’s not just bottom inset. It’s iPhone X status bar too. After updating, I disabled bottom inset and saw the same issue within the landscape games. I changed the status bar to iPad style and checked the game. Now it was perfect. Re-enabled bottom inset while leaving iPad status, issue came back. So conclusion, it’s both the bottom inset and ipx status style.

**Comment by ryannair05** [comment]
Version 1.3.0 fixes the issue. The code that broke this was activated with the iPhone X statusbar or bottom inset.

**Comment by batfirex2** [comment]
Thanks. It works perfect now.
