### ISSUE TITLE
IMessage unable to delete text 

### ISSUE THREAD

**Issue by xxHoBoZxx** [ryannair05/Little11#23]
![348311DC-696A-43A6-8D2A-82DC444B4E93](https://user-images.githubusercontent.com/32913594/76090645-8da45b00-5f81-11ea-8e29-2325c78ac6f8.png)

The confirmation to delete text is not showing fully. I disabled Little11 with iCleaner and it works. Also tried turning off the bottom insert (which I think is the problem) and still can’t delete text. iPhone 8 13.2.3 and Little11 version 1.2.1

**Comment by xxHoBoZxx** [comment]
After some investigating it seems this bug and the bug where some apps like PayPal I am unable to click on the back arrow to go back a screen goes away when using the iPad or the Default statusbar. Why the iPhone X statusbar affect the bottom of the iMessages app only the dev will have a clue.

**Comment by xxHoBoZxx** [comment]
I was able to bypass this bug by using the "Default statusbar" and "No bottom insert" and installing StausbarXS from Cydia. I will wait for an update to see if the dev can fix this, so I can use Little11 only and get rid of the other tweak.

**Comment by ryannair05** [comment]
There issues have been fixed in Version 1.3.0.
