### ISSUE TITLE
Home button haptic return

### ISSUE THREAD

**Issue by lberrezoug** [ryannair05/Little11#26]
Hi,
Can you please add home button haptic return.
iPhone 7
iOS 13.3.1

**Comment by ryannair05** [comment]
This an issue causes by other tweaks and not Little11 itself, as shown by issue #11. The most common conflicting tweaks are Cercube and Gyration, but any tweak hooking into  com.apple.backboardd can be the culprit.

**Comment by lberrezoug** [comment]
Thank you very much, I deleted all the tweaks I left only Little11 and my probably has been solved.  I'll try to find out later who's causing the conflicting.
