### ISSUE TITLE
Wrong device identification causes problems

### ISSUE THREAD

**Issue by MrGigiTheBunny** [ryannair05/Little11#32]
First, I love this tweak! But its a little annoying in some apps. But Zebra identifies my iphone 7 as an iphone 11, I cant provide a screenshot right now because I have a bug (idk what, but it isn't your tweaks fault).

Because of the wrong identification some apps and games wont show up correctly. For example: I’m No Demon.
The game shifts halfway to the left side because it thinks I have a larger screen.

I hope you can fix this because it is very annoying.

**Comment by ryannair05** [comment]
Version 1.3.0 fixes this issue.

**Comment by MrGigiTheBunny** [comment]
I noticed, thanks!
