### ISSUE TITLE
Little11 spoof issues

### ISSUE THREAD

**Issue by alian2plus** [ryannair05/Little11#34]
Hi, 
I just noticed that little 11 causes spoofing issues with other paid apps which requires to be in the same iPhone that I use.
ex: my iPhone is 8Plus when I bought the (x) tweak , but little 11 spoofs as if it was iPhone X instead of being 8Plus .
And the (x) tweak won’t be activated till I disable your tweak through I cleaner.

Love your tweak.

**Comment by ryannair05** [comment]
Version 1.3.0 fixes the issue.
