### ISSUE TITLE
[bug] Facebook app and iPhone X/iPad statusbar glitch

### ISSUE THREAD

**Issue by keremy** [ryannair05/Little11#4]
as stated here on this reddit thread https://www.reddit.com/r/jailbreak/comments/dx3j4l/question_while_in_facebook_and_only_facebook/?utm_source=share&utm_medium=ios_app&utm_name=iossmf

when X status bar or iPad statusbar is enabled and you scroll down on the comment section in Fb app, it glitches and you can’t use the app. only solution is to kill the app and restart

**Comment by ryannair05** [comment]
This should be fixed in Version 1.2.0. Can you please confirm?

**Comment by ryannair05** [comment]
This issue has been fixed.
