### ISSUE TITLE
Apps zoomed out on iPhone 7 iOS 13.4.1

### ISSUE THREAD

**Issue by ProtonyteTV** [ryannair05/Little11#45]
my apps zoomed out since i update it on 1.2.1 on 1.2.0 its fine 
![IMG_0004](https://user-images.githubusercontent.com/58014302/78984753-a643fa00-7b59-11ea-92a1-2a5e5d910949.PNG)
![IMG_0009](https://user-images.githubusercontent.com/58014302/78984762-a9d78100-7b59-11ea-8a26-fea93ee82e13.PNG)
![IMG_0006](https://user-images.githubusercontent.com/58014302/78984764-ab08ae00-7b59-11ea-8b9d-99f904603e33.PNG)
![IMG_0007](https://user-images.githubusercontent.com/58014302/78984773-ae9c3500-7b59-11ea-90e7-7c787bbc502a.PNG)
![IMG_0008](https://user-images.githubusercontent.com/58014302/78984790-b52aac80-7b59-11ea-8a0f-70f3ab209714.PNG)
![IMG_0005](https://user-images.githubusercontent.com/58014302/78984792-b65bd980-7b59-11ea-8815-fadd299cf50d.PNG)

**Comment by ryannair05** [comment]
Version 1.3.0 fixes this issue
