### ISSUE TITLE
haptic feedback stopped working

### ISSUE THREAD

**Issue by aestheticsglowexe** [ryannair05/Little11#47]
Im on ios 13.3 ip8+
Haptic feedback stopped working right after installing little11

**Comment by Mr-Bobby** [comment]
I have the same issue on iPhone 7 Plus, is it to do with preferences or is it a bug?

**Comment by SijanC147** [comment]
This seems to be a recurring issue with a select number of other tweaks, as suggested in #11 where they mention Cercube and Gyration, I've just that same thing happen to me after installing AutoTouch on iPhone 7 Plus. 

So it could be any one of those tweaks if you have them installed, or possibly another tweak that conflicts in the same way.

**Comment by ryannair05** [comment]
With help from #82 this issue has been fixed in version 1.5.0
