### ISSUE TITLE
[request] add global enable / disable for little11

### ISSUE THREAD

**Issue by Inc0ns1st3nt** [ryannair05/Little11#5]
As a user of little11, I have to say it served its purpose very well.

However, as a developer myself, I find myself in a situation where I requires to 
sometimes switch between iPhone X gestures, and my original iPhone 6s gesture.

It would be a greatly appreciated if this feature, where the users can globally enable and disable for little11, is implemented.

**Comment by ryannair05** [comment]
This has been added in the version 1.3.0 of Little11.
