### ISSUE TITLE
Instagram 

### ISSUE THREAD

**Issue by Habeel1** [ryannair05/Little11#51]
Cant choose photos to upload and when try to share something share button doesnt appear 
![Uploading 24E173E8-546C-4378-BCD7-BAD7A9A7C5BF.jpeg…]()

**Comment by dinouse** [comment]
![image](https://user-images.githubusercontent.com/62304158/79558459-c3874400-80d6-11ea-9056-65806a29278b.png)
Statusbar glitch. There was a black line at the top.

**Comment by ryannair05** [comment]
This has been fixed in Version 1.5.0
