### ISSUE TITLE
“No Gestures While Using Keyboard” Don’t Work

### ISSUE THREAD

**Issue by lolailo81** [ryannair05/Little11#57]
When this option is checked, it continues to work with keyboard
![E0EE411E-51D9-4C79-8A71-E4496F1BF52A](https://user-images.githubusercontent.com/38249493/80287002-260fbe00-872f-11ea-84b6-1bca04b0c55b.jpeg)

**Comment by ryannair05** [comment]
The feature is currently not supported on iOS 13.4 and up. Compatibility will hopefully be added in the future.

**Comment by lolailo81** [comment]
Ok ok, thanks very much. Great job!
