### ISSUE TITLE
[Bug] Home Button Haptic Feedback disabled on iPhone 7 Plus

### ISSUE THREAD

**Issue by iGerman00** [ryannair05/Little11#6]
After installing this, the home button fails to give any feedback, thus making it really uncomfortable to use. It still works but it’s unusable like that, you don’t know when you actually pressed it

**Comment by ryannair05** [comment]
Do you use the tweak Cercube?

**Comment by iGerman00** [comment]
Yep. Is it the cause? How come?

**Comment by ryannair05** [comment]
I can not recommend this solution, and I don't know if this will stop any part of Cercube from working, but you can go to Filza, navigate to /Library/MovieSubstrate/DynamicLibrares/ open CercubeServices.plist, and then remove com.apple.backboardd from the Bundles and respring to fix the conflict with Cercube.

**Comment by ryannair05** [comment]
As this is an issue for the developer of Cercube to fix in his tweak, I am closing this issue.
