### ISSUE TITLE
New issue on ig 

### ISSUE THREAD

**Issue by Mikisavage** [ryannair05/Little11#60]
![A968904C-6C27-419D-9F2E-2DB2058FAAA5](https://user-images.githubusercontent.com/64377250/80321239-d824b400-881b-11ea-877b-787bfb5c544a.jpeg)

**Comment by dinouse** [comment]
same goes here

**Comment by Adamsurev** [comment]
Same

**Comment by iTer99** [comment]
> same goes here



> Same

Did you enabled bottom bar ?

**Comment by dinouse** [comment]
> > same goes here
> 
> > Same
> 
> Did you enabled bottom bar ?

yup

**Comment by ryannair05** [comment]
This has been fixed in Version 1.5.0

**Comment by dinouse** [comment]
GREAT!
