### ISSUE TITLE
Major problem with instagram.

### ISSUE THREAD

**Issue by LegendJC** [ryannair05/Little11#61]
I have a iPhone 6s and am running iOS 13.4.1 checkra1n. When I have little 11 enabled all of the instagram posts are zoomed not allowing me to see them fully.

**Comment by ryannair05** [comment]
Can you provide screenshots of the issue? I have not seen any other reports or information about this.

**Comment by ryannair05** [comment]
Version 1.5.0 is believed to fix this issue
