### ISSUE TITLE
Instagram top context bar clashes with iPX status bar option

### ISSUE THREAD

**Issue by arbirchy** [ryannair05/Little11#75]
![image](https://user-images.githubusercontent.com/58096995/83317839-7af29880-a1f5-11ea-827c-7f096ae6c6d1.png)

In the image above, the Instagram top bar and the iPX status bar (emulated by Little11) clash graphically. I've tried turning compatibility and device spoofing on and off individually- and it doesn't seem to fix the issue. I'm on an iPhone 6s, iOS 13.5, and using Rocket- however, this issue persists in iOS 13.4.1 and using vanilla Instagram.

Is there a way to fix this or am I missing something?

**Comment by ryannair05** [comment]
This has been fixed in Version 1.5.0
