### ISSUE TITLE
Lockscreen shortcuts appears on notification center 

### ISSUE THREAD

**Issue by MaceUD** [ryannair05/Little11#76]
Hi and thank you for this tweak!

I have spotted a bug for lockscreen shortcuts (flashlight and camera). They appears in the Notification Center when you scroll it from the top of the iPhone. 

This happens for me on iPhone 8 iOS 13.5

![008AA9A1-D8E9-4AC0-91AD-0C10072B3920](https://user-images.githubusercontent.com/64008256/83354083-25ce9800-a357-11ea-9258-597875c2f033.png)

Sincerely

**Comment by ryannair05** [comment]
I may be misunderstanding your bug report, but the lockscreen toggles are supposed to be there in the notification center. Them being there is not a bug.
