### ISSUE TITLE
[Bug] Little11 issue with "double click to install" apps and screenshot

### ISSUE THREAD

**Issue by kegobass** [ryannair05/Little11#8]
I am having issues with Little11 where I cannot "double click to install" apps or take a screenshot (Power/up button) on iPhoneX iOS 13.3.  I decided to wipe my iPhone and freshly installed checkra1n and Cydia and only Little11 and I still have the issue.  Others are reporting the same issue on Reddit (r/jailbreak).  Thanks!

**Comment by ryannair05** [comment]
Hi, can you check to see if this issue is fixed in the latest version? I changed something that I believe fixes this issue. Thank you!
