### ISSUE TITLE
Face ID animations not working properly 

### ISSUE THREAD

**Issue by marleyqp** [ryannair05/Little11#93]
When the Face ID animation is enabled, the icon will often not show up or be enlarged. See picture.
![081C8E76-A501-4984-9D2C-69DA8D8A0B9C](https://user-images.githubusercontent.com/58849055/92332296-bf06fc00-f074-11ea-9fa5-bfca78eea72c.jpeg)

**Comment by ryannair05** [comment]
That is odd. What device and iOS version?

**Comment by marleyqp** [comment]
iPhone 8, 13.6.1
