### ISSUE TITLE
Cropping & Crowding in Snapchat on iPhone 8

### ISSUE THREAD

**Issue by paullvu** [ryannair05/Little11#97]
Upon opening Snapchat on an iPhone 8, the iPhone X status bar battery comes into contact with the floating toolbar in the top right corner on the camera page of snapchat. 
And also when opening chats,the top half of the status bar is immediately cropped out, making it difficult to tell the time, battery percentage, etc.

I have tried to use Compatibility Mode and Choicy independently and at the same time, and both problems persist.

**Comment by ryannair05** [comment]
Unfortunately, Snapchat issues will not be fixed due to their bans when the app is modified.
